avatar:
  url: /images/avatar.png
  rounded: true
  opacity: 1

banner:
  enable: true
  title: è‡­è‡­ã®å°ç«™
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

social:
  #  - name: QQ
  #    link: https://ti.qq.com/open_qq/index2.html?url=mqqapi%3a%2f%2fuserprofile%2ffriend_profile_card%3fsrc_type%3dweb%26version%3d1.0%26source%3d2%26uin%3d3285956207
  #    icon: icon-qq-line
  #    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/ssmzhn
    icon: icon-github-line
    color: "#6e5494"
#  - name: å¾®åš
#    link: https://weibo.com/jizhideyunyoujun
#    icon: icon-weibo-line
#    color: "#E6162D"
#  - name: è±†ç“£
#    link: https://www.douban.com/people/yunyoujun/
#    icon: icon-douban-line
#    color: "#007722"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: http://music.163.com/m/user/home?id=1790526375
    icon: icon-netease-cloud-music-line
    color: "#C20C0C"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/she-sha-ming-zi-hao-ni/
    icon: icon-zhihu-line
    color: "#0084FF"
  - name: å“”å“©å“”å“©
    link: https://b23.tv/n2PyuM
    icon: icon-bilibili-line
    color: "#FF8EB3"
  # - name: POPI
  #   link: https://www.popiapp.cn/elpsycn
  #   icon: icon-questionnaire-line
  #   color: "#525252"
  #  - name: å¾®ä¿¡å…¬ä¼—å·
  #    link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
  #    icon: icon-wechat-2-line
  #    color: "#1AAD19"
  - name: Twitter
    link: https://twitter.com/ssmzhn12138
    icon: icon-twitter-line
    color: "#1da1f2"
  - name: Telegram
    link: https://t.me/NameSetter
    icon: icon-telegram-line
    color: "#0088CC"
  #  - name: Telegram Channel
  #    link: https://t.me/elpsycn
  #    # icon: icon-telegram-fill
  #    icon: icon-telegram-line
  #    color: "#0088CC"
  - name: E-Mail
    link: mailto:ssmzhn@163.com
    icon: icon-mail-line
    color: "#8E71C1"
      #  - name: Travelling
      #    link: https://travellings.link
      #    icon: icon-train-line
      #    color: black
reward:
  enable: false
pages:
  - name: å°ä¼™ä¼´ä»¬
    url: /links
    icon: icon-genderless-line
    color: dodgerblue
notice:
  enable: true
  content: æ¥äº†å°±çœ‹çœ‹å†èµ°å§ï¼
comment:
  enable: true
  tips:
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œå»ºè®®è·³è½¬ GitHub Issues è¯„è®ºã€‚
    - è‹¥æ²¡æœ‰æœ¬æ–‡ Issueï¼Œæ‚¨å¯ä»¥ä½¿ç”¨ Comment æ¨¡ç‰ˆæ–°å»ºã€‚
  candidates:
#    - valine
    - utterances
utterances:
  enable: true
#  src: https://utteranc.es/client.js
  repo: ssmzhn/ssmzhn.github.io
  issue-term: pathname
  # label: comment
  theme: github-light
#  crossorigin: anonymous

#<script src="https://utteranc.es/client.js"
#        repo="ssmzhn/ssmzhn.github.io"
#        issue-term="pathname"
#        theme="github-light"
#        crossorigin="anonymous"
#        async>
#</script>
footer:
  since: 2021
  live_time:
    enable: true
    prefix: è¿™ä¸ªåšå®¢çˆ¬äº†
    suffix: ğŸ˜…
    start_time: "2021-08-15T17:23:40"

wordcloud:
  enable: true

codeblock:
  copy_btn: true
katex:
  copy_tex: true
  global: false

#é»˜å“€
mourn:
  enable: true
  days:
    - "4-5"
    - "12-13"
    - "9-18"
    - "5-12"

head:
  css:
    fonts: 
      - https://fonts.loli.net/css?family=Saira
      - https://fonts.loli.net/css?family=JetBrains%20Mono

font:
  cdn:
    enable: true
    lib:
      - https://fonts.loli.net/css?family=Saira
      - https://fonts.loli.net/css?family=JetBrains%20Mono
  serif:
    family: '''Songti SC'', ''Noto Serif SC'', STZhongsong, STKaiti, KaiTi, Roboto, serif'
    weight: 900
  sans_serif:
    family: 'Saira, ''PingFang SC'', ''Microsoft YaHei'', Roboto, Arial, sans-serif'
    weight: 400
  monospace:
    family: '''JetBrains Mono'', ''Source Code Pro'', ''Courier New'', Courier, Consolas, Monaco, monospace'

